version: '3.7'
services:
  app:
    container_name: sahtelPlusPlus
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - hk_system
  db:
    container_name: hk_system_db
    build:
      context: ./
      dockerfile: Dockerfile-Postgres
    ports:
      - 10000:5432
    env_file:
      - .env
    volumes:
      - hk_system_db:/var/lib/postgresql/data
    networks:
      - hk_system

volumes:
  hk_system_db:

networks:
  hk_system:
    driver: bridge