version: '3.7'
services:
  app:
    container_name: sahtelPlusPlus
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: sahtelPlusPlus_db
    build:
      context: ./
      dockerfile: Dockerfile-Postgres
    ports:
      - 10000:5432
    env_file:
      - .env
    volumes:
      - sahtelPlusPlus_db:/var/lib/postgresql/data

volumes:
  sahtelPlusPlus_db: